### ISSUE TITLE
Logging purge interval is ignored

### ISSUE THREAD

**Issue by thenadz** [thenadz/document-gallery#26]
Purge happens every 24hrs (ish) no matter what purge interval is set to.

**Comment by demur** [comment]
I believe culprit is settled at [document-gallery/inc/class-logger.php on line 135](https://github.com/thenadz/document-gallery/blob/master/inc/class-logger.php#L135)
and can be cured with these changes:
`if ( ! is_null( $fields ) && $time `**<=**` ( `**intval(**`$fields[0]`**)**` + $purge_interval ) ) {`

**Comment by thenadz** [comment]
I believe you are indeed correct! :+1: 

I think I'll actually take the opportunity to simplify that logic a bit though -- line 135 is replaced with:
`if ( ! is_null( $fields ) && $purge_time > intval( $fields[0] ) ) {`

and

`$purge_time = $time - $options['purge_interval'] * DAY_IN_SECONDS;`

Sound good?

**Comment by demur** [comment]
Sounds good except for the comparison operator; I still believe there should be *less than or equal* or at least *less than*
What are Your thoughts?
