### ISSUE TITLE
Configure Document Gallery tooltip persists even after saving settings

### ISSUE THREAD

**Issue by katkhalifa** [thenadz/document-gallery#31]
I can't seem to dismiss this tooltip even after configuring and saving settings.  It is blocking my view of other plugins on the plugins page-- very annoying.

How can I get rid of this tooltip?
![document-gallery-tooltip-issue](https://cloud.githubusercontent.com/assets/14379221/12355601/b6702064-bb6b-11e5-83f7-9983769a68be.jpg)

**Comment by thenadz** [comment]
Hi katkhalifa,

That is definitely annoying! There is supposed to be an "X" on that dialog to dismiss it.

Can you do me a favor? If you hit F12 on your keyboard, you should get a console at the bottom of your browser. With that open, if you navigate to the plugins index page are any errors logged?

Also, can you please tell me what browser you are using?

**Comment by katkhalifa** [comment]
Hi Dan,

Thanks very much for the quick response.  Hope it’s easy to fix.

I’m using a Mac (OS X 10.9.5) with Firefox (latest version)— with firebug installed.

Here’s what I see when I navigate to the plugins index page:

**Comment by katkhalifa** [comment]
Hi Dan,

This is also happening within the Settings area:

**Comment by thenadz** [comment]
@katkhalifa, were you intending there to be images in your last two posts?

**Comment by katkhalifa** [comment]
Sorry, I forgot that these were also posts.  I will upload them.

**Comment by katkhalifa** [comment]
I added the images to the above posts.

**Comment by thenadz** [comment]
Thanks, @kathalifa. Would you mind disabling all of your plugins except DG and seeing whether you then have an X on the pop ups? I believe one of your other plugins may be changing thugs it shouldn't.

**Comment by katkhalifa** [comment]
Found it— WP Events Plus.  I will see if they have an update—

**Comment by katkhalifa** [comment]
Thanks for your help— updating the offending plugin seems to have taken care of it.

Regards,
  Kathy

**Comment by thenadz** [comment]
Fantastic! Glad to be of some help! :)
