### ISSUE TITLE
Ability to define gallery contents by category

### ISSUE THREAD

**Issue by mkrause01** [thenadz/document-gallery#32]
It would be great to be able to group and categorize the Media Library contents and then define a Document Gallery gallery as, for example, [dg order="DESC" order="DESC" new_window="true" descriptions="false" fancy="false" orderby="name" columns="5" limit="25" attachment_pg="false" paginate="true" category="newsletters"].  Then, as new Media Library files are added to the "category", the contents of the Document Gallery gallery would automatically include the new additions to the category.

**Comment by thenadz** [comment]
Hi @mkrause01,

The functionality you are requesting is already supported in DG. Please see the excerpt from the documentation below.

-Dan

(https://wordpress.org/plugins/document-gallery/installation/)
> Categories/Custom Taxonomy Option (New in Version 1.4)
> 
> With the categories option you are able to select attachments based on their assigned category or 
> any other custom taxon. Categories or any custom taxon can be referenced simply by including
> category=category_value or taxon_name=taxon_value. Multiple values for a single taxon may be
> separated by commas. Note that if a taxon value contains spaces then the entire comma- delimited
> list must be quoted.
